networks:
  backend:
    name: "${COMPOSE_PROJECT_NAME}"
services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}.nginx"
    build:
      context: "../../docker/nginx"
      target: "local"
    image: "brickstack-laravel-template/nginx"
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - "../../src:/var/www:cached"
    depends_on:
      - "php-fpm"
    networks:
      - "backend"
  php-fpm:
    container_name: "${COMPOSE_PROJECT_NAME}.php-fpm"
    build:
      context: "../../docker/php-fpm"
      target: "local"
    image: "brickstack-laravel-template/php-fpm"
    volumes:
      - "../../src:/var/www:cached"
      - "./my-php.ini:/usr/local/etc/php/conf.d/my-php.ini"
    environment:
      TZ: "Asia/Tokyo"
#    depends_on:
#      - "db"
    networks:
      - "backend"
#  db:
#    container_name: "${COMPOSE_PROJECT_NAME}.db"
#    image: "mysql/mysql-server:8.0.32"
#    environment:
#      MYSQL_USER: "${MYSQL_USER}"
#      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#      MYSQL_DATABASE: "${MYSQL_DATABASE}"
#      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      TZ: "Asia/Tokyo"
#    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
#    volumes:
#      - "db:/var/lib/mysql"
#      - "./init/:/docker-entrypoint-initdb.d"
#    ports:
#      - "${DB_PORT:-3333}:3306"
#    networks:
#      - "backend"
#  redis:
#    container_name: "${COMPOSE_PROJECT_NAME}.redis"
#    image: "redis:alpine"
#    ports:
#      - "${FORWARD_REDIS_PORT:-6379}:6379"
#    volumes:
#      - "redis:/data"
#    networks:
#      - "backend"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      retries: 3
#      timeout: "5s"
#  minio:
#    container_name: "${COMPOSE_PROJECT_NAME}.minio"
#    image: "minio/minio:latest"
#    environment:
#      MINIO_ROOT_USER: "asdfghASDFGH"
#      MINIO_ROOT_PASSWORD: "asdfgh123456"
#    entrypoint: "bash"
#    command: '-c "minio server /data --address :9000 --console-address :9001;"'
#    volumes:
#      - "./s3/data:/data"
#    ports:
#      - "${MINIO_PORT_1:-9000}:9000"
#      - "${MINIO_PORT_2:-9001}:9001"
#    networks:
#      - "backend"
#  mailpit:
#    container_name: "${COMPOSE_PROJECT_NAME}.mailpit"
#    image: "axllent/mailpit:v1.9"
#    ports:
#      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
#      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
#    environment:
#      TZ: "Asia/Tokyo"
#    networks:
#      - "backend"
#volumes:
#  db:
#  redis:
